mozilla/telemetry-dashboard

src/dashboard.js

Fix $checkbox is undefined when trying to select aggregates that don't exist

---

index.html
style/dashboard.css

This is ugly. A better solution would be writing a function in dashboard.js ... that could be reused  for other unreliable data some other time.

Add an ugly warning about unreliable Nightly 39 data from unified pings

---

chromehangs/index.html
mainthreadio/index.html
slowsql/index.html

Fixes [bug 1162265](https://bugzilla.mozilla.org/show_bug.cgi?id=1162265).

Fix mixed-content errors when accessing some dashboards using https.

---

src/dashboard.js

71d6fbe8751fed50d329df8d5ad575135eaefb6e was rebased from chart-fixes 2, which mixed up the merge a bit and resulted in an error.

Fix future date filtering.

---

index.html

Better labels for buttons

---

index.html
src/dashboard.js
style/dashboard.css

* Align slider with the chart and improve styling.
* Fix rendering on old WebKit browsers.
* Clean up the slider code a little bit.
Currently live at http://anthony-zhang.me/telemetry-dashboard/.

Range slider tweaks.

---

index.html

Add warning that recent versions seem to be missing submissions.

---

advanced/index.html
advanced/src/dashboard.js
advanced/style/dashboard.css
src/dist.js

Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1181361
Now live at http://staging.telemetry-dashboard.divshot.io/

Remove "end"  field from tables and exported files, center align table columns

---

index.html

Changes live at http://development.telemetry-dashboard.divshot.io/.

Add link to graphics telemetry dashboard.

---

dist.html
evo.html
src/dashboards.js
src/dist.js
src/evo.js
style/dashboards.css
v1/telemetry.js

Implements fixes and features from from #93:
* Simpler timezone handling - just convert it into a date string (this also fixes the legend and the date range picker getting out of sync).
* Make the search box bigger by removing the unnecessary icons.
* Sort the version selector better and add separators to make the list easier to read.
* OS selector shows the OSs themselves when they are all selected, like "Windows" when all the Windows versions are selected.
* Update the finished feedback items.
Still to be done:
* Table view for dist dash.
* Add option to select an entire channel at once in the evolution dash.
Now live at http://production.telemetry-dashboard.divshot.io/.

Bugfixes 2

---

README.md
histogram-simulator/index.html

New README: https://github.com/Uberi/telemetry-dashboard/tree/doc-improvements#readme
Now with deployment instructions, development environment setup, and more!

Documentation Improvements

---

dist.html
new-pipeline/src/dist.js
src/dashboards.js
src/dist.js

Now live at http://production.telemetry-dashboard.divshot.io/

Add table view to v2 histogram dashboard.

---

index.html

Link to slides as well from the landing page.

Link to slides added from #106 (already edited on Air Mozilla).

---

v2/v1-shim.js

This is basically the v1-shim branch, but without any changes to the old/advanced dashboard (in the other branch, the old dashboard was adapted to use the shim with some small changes).

Add v1-shim.js from the v1-shim branch.

---

dist.html
evo.html
index.html
new-pipeline/dist.html
new-pipeline/evo.html

Change reporting link to the GitHub issues tracker.

---

new-pipeline/dist.html
new-pipeline/src/dist.js

Only show sort keys option for keyed histograms.

---

new-pipeline/src/dashboards.js
src/dashboards.js

Only use the select all option for the aggregate and OS selectors.

---

new-pipeline/src/dashboards.js

Ref: https://github.com/mozilla/telemetry-dashboard/issues/114
The separators look a bit weird right now, but that's already fixed in #113.

Move unknown products into their own section.

---

new-pipeline/dist.html

See #115 for details.
The third keyed histogram plot aligns to the right instead of the left, and messes up the layout.

Fix layout issue with keyed histograms not rendering properly.

---

new-pipeline/src/dist.js

Make pie chart bucket labels better.
They default to True, False, and Other now.

Better bucket labels.

---

new-pipeline/dist.html
new-pipeline/src/dist.js

Allow export of comparison values.

Support export within comparison view.

---

dist.html
evo.html
new-pipeline/dist.html
new-pipeline/evo.html
new-pipeline/src/dashboards.js
new-pipeline/src/dist.js
new-pipeline/src/evo.js
new-pipeline/style/dashboards.css
src/dashboards.js
src/dist.js
src/evo.js
style/dashboards.css

Small fixes

---

new-pipeline/src/dist.js

Invert boolean bucket pie chart labels. Fixes #156

---

histogram-simulator/simulator.js
new-pipeline/src/dashboards.js
new-pipeline/src/dist.js
new-pipeline/src/evo.js
src/dashboards.js
src/dist.js
src/docs.js
src/evo.js
v2/telemetry.js
v2/v1-shim.js

Make all the dashboard code conform better to the [style guide](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style#JavaScript_practices).
There are also a few semantic changes to make the code a bit neater, but the functionality should remain exactly the same.

Code cleanup

---

new-pipeline/src/dist.js

Add better missing data message.

---

new-pipeline/src/dashboards.js
src/dashboards.js

Ref: #176.
Now live at http://planner-frog-12114.bitballoon.com/.

Make selectors scroll the last selected items into view.

---

histogram-simulator/simulator.js

`telemetry.js`'s `Telemetry.Histogram` constructor has been updated - update the histogram simulator to take these changes into account.
Test site: http://physiotherapist-canary-26213.bitballoon.com/

Update histogram simulator (fixes #181).

---

README.md

Update documentation to reflect deployment changes

---

README.md
advanced/src/jquery.telemetry.js
index.html
new-pipeline/src/dashboards.js
src/dashboards.js
test.js

Adds label for Mac OS X 10.11 El Capitan

---

advanced/src/jquery.telemetry.js
test.js

Split out to separate PR as requested by @vdjeric

Remove trailing whitespace

---

wrapper/README.md
wrapper/telemetry-wrapper.css
wrapper/telemetry-wrapper.js

This has reached 1.0. Seems like a good time to get it pushed out onto telemetry.mozilla.org so the dashboard generator can find the scripts where it should be looking.

bug 1219790 - Make a low-frills, high performance plotter. r?vladan

---

v2/telemetry.js

If you have a long-lived script, you will have to reload the page so that
Telemetry.init can be called again when another date's data is available.
Without this, calling Telemetry.init over and over again could cause callbacks
to be called when the internal version->date structures are in an inconsistent
state.

Ignore subsequent calls to v2/telemetry.js' Telemetry.init().

---

new-pipeline/src/dist.js

The CSV contains a lot of repetition, but such is the nature of the format.
Issue #193

Support export of keyed histograms on new-pipeline/dist.html

---

dashboard-generator/generator.js
dashboard-generator/index.html
dashboard-generator/style.css
index.html
new-pipeline/src/evo.js
wrapper/telemetry-wrapper.css
wrapper/telemetry-wrapper.js

The blogpost isn't live yet, but it has been written.

dashboard-generator: To-order, on-demand, hot and cold running dashboards

---

chromehangs/chromehangs.js
distribution/js/distribution.js
index.html
slowsql/slowsql.js

See fhr-dev [thread](https://mail.mozilla.org/pipermail/fhr-dev/2015-November/000672.html).

Update dashboards to point to data produced in new-dev IAM.

---

new-pipeline/src/dist.js

dash: If the data's been sanitized away, don't use its label.

---

new-pipeline/src/crash-summary.js

60 * 60 == 3600, not 360

---

addon-perf/index.html
chromehangs/index.html
lib/jquery.csv-0.8.2.js
slowsql/index.html

Two things:
1. jquery-csv moved, so any dashboard using that fails (b2c2c45). Pulled release 0.8.2 from the continuation and added it to /lib.
2. "fork me" link was outdated (b6a6310).

Updated broken links

---

update-orphaning/index.html

@chutten, if you could review/merge or forward, I'd appreciate it. Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-dashboard/236)

Add a page title and version distribution pie chart to the update orphaning dashboard

---

addon-recommender/js/main.js

r? @vitillo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-dashboard/241)

Fix the addon recommender page on Chrome

---

v2/telemetry.js

Issue #242
Some versions have been long-lived enough for clients to have submitted
data from them over _years_. This results in a long request URL at the aggregator,
which doesn't handle it well.
So assert if we get a long one, and split large submission-date-dominated
urls in half before requesting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-dashboard/244)

Handle large urls by splitting them in half.

---

addon-recommender/js/main.js

The top 10 addons list is fetched from addons.mozilla.org
using the provided API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-dashboard/245)

Suggest the global top 10 addons if none is installed

---

update-orphaning/index.html

Also, take spohl's name off the page so he stops getting bothered about this thing.
needs-review: @chutten
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-dashboard/261)

Bug 1290155 - Show update orphaning data from the most recent week
