mozilla/telemetry-dashboard

v1/telemetry.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1119876
I tested this change manually by dropping this file into my local webserver and hacking my `/etc/hosts` to point `telemetry.mozilla.org` to `127.0.0.1`.
=> Check for the HTTPS version of releaseURL too

index.html, src/jquery.telemetry.js, style/dashboard.css
* Fix the main screen notice of selection bias.
* Make the filtering system more flexible:
* Add support for "fixed options", which are always implicitly included in the filter, and use this to implement `save_session` filtering.
* Add support for labeling options with values that are not the same as their actual values, and use this to implement friendly OS/version names. For example, "WINNT" is now shown as "Windows", and Darwin "10.0.0" is shown as "10.0.0 (Snow Leopard)".
* Remove the "Any App" option since it is not very useful (previously known as "appName*").
=> Various UI Fixes

index.html
* Tooltops for various options, to clarify things like the difference between the submissions and count.
* Clarify the percentile inaccuracy, as it is actually a linear or geometric interpolation (depending on the histogram kind) within a bucket.
* Add notice about start/end time selection.
Some of the descriptions are going to be made out of date soon by the graphing changes, but they will be updated afterwards to reflect this.
=> Add tooltips, descriptions, and prompts to make the dashboard easier to use

src/dashboard.js, src/jquery.telemetry.js
* Implement all feedback from #68.
* Top level mappings, rename functions, etc.
* Fix state loading from hash (previously the dropdowns would be blank).
* Sort Windows versions by release date, add in Windows 10 tech preview and Windows 95.
=> UI fixes part 2.

index.html, src/dashboard.js, v1/telemetry-worker.js, v1/telemetry.js
* Web Workers allow us to do the heavy lifting off of the UI thread, which keeps the window responsive.
* There is still a little bit of stutter when the charts are being drawn, which is unavoidable AFAIK.
* This adds a file to the Telemetry distribution called `telemetry-worker.js`, the background worker, as well as functions like `Telemetry.doAsync` for callback-style async worker operations.
* The worker is only used for histogram precomputation and entry counting, since those were the only real hotspots.
* A small optimization to bucketing also caused a gigantic speedup in histogram evolution creation.
=> Use Web Workers for background processing

index.html, src/dashboard.js
* Don't draw points at all where there aren't enough submissions.
* Update the URL hash properly when filters are added while the locking is off.
* Make newly added filters duplicate the last filter rather than the first one.
* Fix a bug in which there would not be any filters for a series that was added at first.
=> Small chart fixes

src/dashboard.js
* Ignore points that have invalid dates far into the future (based on the system clock, with a 1 year buffer in case the clock is wrong).
* Make the histogram bar colors consistent every time.
=> Various fixes to charts.

src/dashboard.js
When the timescale only shows one point, the scatter plot doesn't know what scale to use, and ends up being undefined.
We can specify the scale by adding an endpoint series to the plot.
This is now live at http://anthony-zhang.me/telemetry-dashboard/.
=> Fix display when the timescale is small

index.html, src/dashboard.js, src/jquery.telemetry.js
* Align the aggregate selector and move the Add Series button closer to the filters.
* Ignore Windows_98 as an OS.
* Default to selecting the latest nightly version.
* Currently live [here](http://anthony-zhang.me/telemetry-dashboard/).
=> UI Fixes 3

src/dashboard.js
This works better than using the lesser of the lowest 1% and 100, since before we could have 200 submissions pass the sanitizer. Now, we ensure the shown data excludes the lowest 1% in all cases.
=> Fix data sanitizing to exclude data with the lowest 1% of submission counts

dist.html, src/dist.js
Links to export the current histogram to CSV or JSON. Both formats have bucket ranges and counts for each bucket.
=> Add export links.

dist.html, evo.html, src/dashboards.js, src/dist.js, src/evo.js
* The advanced settings panel will now show "(modified)" when we change advanced settings, and open on load.
* It is no longer possible to select versions that are in different channels in evolution dashboard, like beta to nightly.
* The X-axis label now changes along with the evolution variable.
* Bugfixes for switching between aggregates of different kinds - switching to a flag histogram should automatically select the Mean aggregate, even when it was not previously selected.
Now live on http://production.telemetry-dashboard.divshot.io/
=> Modified settings

v2/telemetry.js
Otherwise, this breaks on HTTPS sites.
=> Change BASE_URL from http to https

v2/telemetry.js
Commit b1140960d72c9e9624a512875b366fbad529666c needs to be temporarily reverted until [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1195802) is fixed.
These changes are already included in #125, so when the bug is fixed, merging #125 will include the changes that were originally made in this commit.
=> Revert "Change BASE_URL from http to https"

new-pipeline/src/dist.js, new-pipeline/src/evo.js, src/dist.js, src/evo.js
Right now, when dashboard pages are resized the aspect ratio of the plot remains the same, which makes things look weird when zooming the page.
By avoiding the `full_width` option, we can manually calculate the chart size to get a smoother result.
Now live at http://staging.telemetry-dashboard.divshot.io/.
=> Make resizing work properly with dynamic plot aspect ratio.

new-pipeline/src/dist.js, new-pipeline/tutorial.html, src/dist.js, v2/doc.md
* Don't trim buckets for table view, and sort comparison measures (#136, #137).
* Add a (none) option for keys so we have something to display when there are fewer than 4 available keys (#139).
* Don't sanitize key list for histograms - always show all of the keys regardless of how many submissions they have (#138).
* Add an example and description for keyed histograms (#140). Keyed histogram support is already documented for Telemetry.js v2 in the API reference.
* Make the labels for enumerated histograms the bucket range values themselves, rather than a range of values (#142).
Now live at http://staging.telemetry-dashboard.divshot.io/.
=> Fixes and features

README.md, index.html, v2/doc.md, v2/telemetry.js
Some sites still don't work with HTTPS, such as Telemetry Alerts.
Also, use the correct URL for the Telemetry.js include in the Telemetry.js v2 documentation.
**NOTE:** do not merge until https://bugzilla.mozilla.org/show_bug.cgi?id=1195802 is resolved.
=> Use HTTPS links where possible

wrapper/README.md, wrapper/telemetry-wrapper.js
First, an augmentation to limit the number of keyed histograms displayed to the `keyLimit` with the most submission counts.
Then a fix to the README to make the example actually look pretty. For some reason I thought we could skip rel="stylesheet" in HTML5, so I let brevity kill correctness.
Then a fix to a regression where only the last key of a keyed histogram would show.
=> 3 more tweaks to telemetry-wrapper

new-pipeline/src/dist.js, wrapper/telemetry-wrapper.css, wrapper/telemetry-wrapper.js
Looks like this: http://people.mozilla.org/~chutten/media/barGroup.PNG
Live version here: http://bit.ly/1QRXUya (the dashgen doesn't work live on that site because the generated dashes all point back to t.m.o)
Covers #130
=> dash+wrapper: Add a "grouped bar" chart for comparing multiple boolean/flag histograms

new-pipeline/dist.html, new-pipeline/src/dist.js, new-pipeline/style/dashboards.css
Doing this in DOM makes the histogram description selectable and wrappable.
Issue #184
=> dash: Add a title to the plot group.

wrapper/telemetry-wrapper.js
Error out visibly only if the data sanitized away was the only data
for an unkeyed histogram.
Issue #208
=> wrapper: warn if sanitize removes all data for a particular key.

wrapper/telemetry-wrapper.css, wrapper/telemetry-wrapper.js
This way you can get to a dist.html or evo.html from a plot if you want to
change the params a bit.
The dashes' application filter does not support 'no filter', so translate that
to 'Firefox!Fennec' to get most of the way there.
Issue #199
=> wrapper: Linkify plot titles to ref a dashboard configured the same way.

new-pipeline/src/evo.js
It thought that only enumerated plots needed % signs.
Issue #212
=> dash: The mouseover text isn't using % signs for boolean plots.

wrapper/telemetry-wrapper.js
It can work just fine with counts. For the mouseover, it actually needs them.
Issue #214
=> wrapper: d3pie doesn't need precomputed %ges

new-pipeline/src/dist.js
When the set of histograms is empty, `histograms[0]` is not defined. Example of `TypeError`: https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2016-01-19&keys=__none__!__none__!__none__&max_channel_version=aurora%252F45&measure=LOOP_SHARING_ROOM_URL&min_channel_version=null&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2015-12-17&table=0&trim=1&use_submission_date=0
=> Fix empty histograms set

new-pipeline/src/evo.js
Ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1245114
The assertion is not necessary since we don't really need the histogram kind at that point. When there are no dates with available aggregate data, we should simply display a blank result rather than giving an assertion error.
=> Fix "uncaught exception: Kind must be specified"

new-pipeline/src/evo.js
As requested by :smaug in #perf - showing upper and lower percentiles make it easier to see certain regressions.
=> Select 5th percentile, median, and 95th percentile by default

update-orphaning/index.html
@chutten - Sorry, I didn't notice this mixed content warning on http://sapohl.github.io/telemetry-dashboard/update-orphaning/ because I didn't check the https:// variant of the URL, but this warning breaks https://telemetry.mozilla.org/update-orphaning/ since it's only served via https://.
=> Fix mixed content warning.

update-orphaning/index.html
1. Reference the responsible person for the dashboard (with email
address).
2. Reference the Spark job that creates the data for the weekly reports.
3. Make it clear in the summary of the page what’s considered
“up-to-date” for each weekly report in the context of this dashboard.
=> Minor improvements to update orphaning dashboard

update-orphaning/index.html
Make update orphaning dashboard aware of users who haven't run Firefox
for at least 2 hours. These should be split out and displayed
separately.
This is to address https://bugzilla.mozilla.org/show_bug.cgi?id=1284933.
needs-review: @chutten
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-dashboard/237)
=> Make update orphaning dashboard aware of min. user usage hours

update-orphaning/index.html
needs-review: @chutten 
We now schedule the weekly Spark job for the update orphaning dashboard
via Airflow. Airflow uses a new URL for the output files. Airflow also
operates on a one-week delay, so we have to drop the most recent date
as an option from the dropdown menu in the dashboard.
Note: older data files will be copied manually to the new location.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-dashboard/238)
=> Make update orphaning dashboard aware of the new Airflow-specific URL

update-orphaning/index.html
needs-review: @chutten 
The update orphaning Spark job is now scheduled to run right after the
longitudinal dataset creation job on Sunday, instead of Wednesday. The
dates need to be adjusted as follows:
Monday: -5
Tuesday: -6
Wednesday: -7
Thursday: -8
Friday: -9
Saturday: -10
Sunday: -11
Note that this is in addition to the 7-day adjustment a few lines below
because of the fact that Airflow schedules these jobs with a one week
delay.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-dashboard/239)
=> Accommodate new weekday when update orphaning Spark job is run

new-pipeline/src/dashboards.js
bit.ly seems to return only http links, so let's detect and fix that.
Issue #229
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-dashboard/230)
=> Use https for shortened links.

crashes/office-dashboard.js
Small fix to show the "no data" graph image on data failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-dashboard/247)
=> #e10s-graph no longer exists, but #e10s-graph1 does

update-orphaning/index.html
This dashboard builds a file name to fetch by using + to concatenate a year, month, and day. If the month is before October, it has to get a 0 prepended, forcing its conversion to a string. But in October or later, when that doesn't happen, the components are all still numbers and + adds them up as numbers instead of concatenating them as strings.
So, here we switch to a method of building the file name string that doesn't care what the types of the components are.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-dashboard/253)
=> Bug 1312420 - Don't try to use + on things that could be either strings or numbers

v2/telemetry.js
This allows me to do this:
```
Telemetry.getEvolution(channel, version, TAB_SPINNER, {os: ["Linux", "Darwin"], e10sEnabled: "true"}, false /* useSubmissionDate */, evolutionMap => {
//...
});
```
Whereas before I could only specify a single OS at a time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/telemetry-dashboard/262)
=> Allow filters to have multiple values
